quantidades = {
    'pacotes': 0,
    'arp': 0,
    'arp_req': 0,
    'arp_rep': 0,
    'ipv4': 0,
    'ipv4_icmp': 0,
    'ipv4_icmp_echo_req': 0,
    'ipv4_icmp_echo_rep': 0,
    'ipv4_tcp': 0,
    'ipv4_tcp_http': 0,
    'ipv4_tcp_https': 0,
    'ipv4_tcp_dns': 0,
    'ipv4_udp': 0,
    'ipv4_udp_dns': 0,
    'ipv4_udp_dhcp': 0,
    'ipv6': 0,
    'ipv6_icmp': 0,
    'ipv6_icmp_echo_req': 0,
    'ipv6_icmp_echo_rep': 0,
    'ipv6_tcp': 0,
    'ipv6_tcp_http': 0,
    'ipv6_tcp_https': 0,
    'ipv6_tcp_dns': 0,
    'ipv6_udp': 0,
    'ipv6_udp_dns': 0,
    'ipv6_udp_dhcp': 0,
}
